### ISSUE TITLE
Accept an object?

### ISSUE THREAD

**Issue by ngryman** [browserify/to-buffer#1]
Hi,

I was just going to write something similar :)
I also need to be able to pass a plain object and get stringified version in a buffer.
Do you think you could add this, or is it out-of-scope?

Thanks!

**Comment by mafintosh** [comment]
I think that might be too clever for this module. This is mostly about not hitting the number constructor by accident.

**Comment by ngryman** [comment]
@mafintosh No problem, I understand. I'll wrap `to-buffer` then :) Thanks!
